# Generated by Django 4.0.10 on 2024-01-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DododexApi', '0002_rename_user_customuser_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinosaur',
            name='feeding',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
